### PR TITLE
gitignore for unecessaries files/folders & Updating excludes on the config

### PR DESCRIPTION
**Pull request by BuKinoshita**

### CODE REVIEW

**Comment by juarezpaf** [comment]
Thank you @BuKinoshita :rocket:

**Comment by BuKinoshita** [comment]
:+1:

**Comment by BuKinoshita** [comment]
Are you using Github master branch as the main host for Gh-pages?

If so, it's better to create a branch for gh-pages, website is down now (can't find css files)

**Comment by juarezpaf** [comment]
@BuKinoshita yeah! We're using `master` branch! Just reverted for now!

**Pull request merged**
